[package]
name = "bassert"
version = "1.0.0"
edition = "2021"
authors = ["Qqwy/Wiebe-Marten Wijnja"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
